server:
    port: 8080
spring:
    datasource:
        password: P@ssword*123
        url: jdbc:postgresql://code4fun.xyz:5432/blogs?currentSchema=blog_dbo2
        username: dev
    flyway:
        password: P@ssword*123
        url: jdbc:postgresql://code4fun.xyz:5432/blogs?currentSchema=blog_dbo2
        user: dev
    jackson:
        deserialization:
            fail-on-unknown-properties: true
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: false
    kafka:
        bootstrap-servers:
            - http://localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            retries: 5
            properties:
                enable.idempotence: true
                max.in.flight.requests.per.connection: 5
                request.timeout.ms: 100
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    mail:
        host: smtp.gmail.com
        username: translatorvamkv1@gmail.com
        password: lcyhfdfjdhahknmu
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
    servlet:
        multipart:
            max-file-size: 25MB
            max-request-size: 25MB
    data:
        redis:
            host: localhost
            port: 6379
            database: 0
            password:
            username: default
management:
    endpoints:
        web:
            exposure:
                include: health
    otlp:
        metrics:
            export:
                enabled: false
        tracing:
            endpoint: ""
    tracing:
        sampling:
            probability: 1.0
        enabled: false
oauth2:
    authorizedRedirectUris:
        - http://localhost:3000/oauth2/

# Email Sender
email:
    registration-confirmation:
        template: registration-confirmation-en.html
        subject: Registration Confirmation
        from: noreply@pezzie.com
        base-url: http://localhost:8080/api/v1/auth/registrationConfirm?token=%s
    forgot-password-email:
        template: password-forgot.html
        subject: New Password
        from: noreply@pezzie.com
        base-url:
app:
    generate-categories: true

flywaypf:
    active: blog_dbo2
#
#springdoc:
#    api-docs:
#        enabled: false
#    swagger-ui:
#        enabled: false
# For development
logging:
    config: classpath:log4j2-spring-dev.xml

outbound:
    identity:
        client-id: 720549923520-qbmtr8g24bptcp90659vh6ffc39j9se6.apps.googleusercontent.com
        client-secret: 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
        redirect-uri: https://blogs-fe-dev.code4fun.xyz/authenticate

api:
    username: admin
    password: 123456

file:
    upload:
        url: https://minio-be.code4fun.xyz

notifications:
    event:
        url: https://notifications-be.code4fun.xyz
jwt:
    expiryMinutes: 60
    expiryDay: 14
    accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
    refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=