spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    flyway:
        enabled: false
    h2:
        console:
            enabled: true
            path: /h2-console

    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 28179558203-kdugdkjaiuljem1ornmiobdua124kok7.apps.googleusercontent.com
                        clientSecret: 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
                        redirect-uri: 'http://localhost:8080/oauth2/callback/google'
                        scope:
                            - email
                            - profile

