spring:
    config:
        import: optional:classpath:.env[.properties]
    datasource:
        password: P@ssword*123
        url: jdbc:postgresql://nocng.id.vn:5432/blogs?currentSchema=blog_dbo2
        username: dev
    flyway:
        password: P@ssword*123
        url: jdbc:postgresql://nocng.id.vn:5432/blogs?currentSchema=blog_dbo2
        user: dev
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
    kafka:
        bootstrap-servers:
            - http://nocng.id.vn:9192
            - http://nocng.id.vn:9292
            - http://nocng.id.vn:9392
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    mail:
        host: smtp.gmail.com
        username: translatorvamkv1@gmail.com
        password: lcyhfdfjdhahknmu
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
    servlet:
        multipart:
            max-file-size: 25MB
            max-request-size: 25MB
    profiles:
        active: dev

# Email Sender
email:
    registration-confirmation:
        template: registration-confirmation.html
        subject: Registration Confirmation
        from: noreply@pezzie.com
        base-url: http://localhost:8080/user/api/v1/auth/regitrationConfirm?token=%s

app:
    generate-categories: true

flywaypf:
    active: blog_dbo2

api:
    username: admin
    password: 123456

file:
    upload:
        url: http://localhost:8081